export const TAG_OPTIONS = [
    { label: 'div', value: 'div' },
    { label: 'ul', value: 'ul' },
    { label: 'li', value: 'li' },
    { label: 'section', value: 'section', description: '文書のセクションを示す' },
    { label: 'article', value: 'article', description: '独立したコンテンツを表す' },
    { label: 'aside', value: 'aside', description: 'コンテンツの補足情報' },
    { label: 'header', value: 'header', description: '文書またはセクションのヘッダー' },
    { label: 'footer', value: 'footer', description: '文書またはセクションのフッター' },
    { label: 'nav', value: 'nav', description: 'ナビゲーションリンクの集合' },
    { label: 'h1', value: 'h1', description: '最も重要な見出し' },
    { label: 'h2', value: 'h2', description: '2番目に重要な見出し' },
    { label: 'h3', value: 'h3', description: '3番目に重要な見出し' },
    { label: 'h4', value: 'h4', description: '4番目に重要な見出し' },
    { label: 'h5', value: 'h5', description: '5番目に重要な見出し' },
    { label: 'h6', value: 'h6', description: '6番目に重要な見出し' },
    { label: 'main', value: 'main', description: '文書の主要な内容' },
    { label: 'figure', value: 'figure', description: '画像や図表のコンテナ' },
    { label: 'figcaption', value: 'figcaption', description: 'figureのキャプション' },
    { label: 'address', value: 'address', description: '連絡先情報' },
    { label: 'table', value: 'table', description: 'テーブル' },
    { label: 'caption', value: 'caption', description: 'テーブルのキャプション' },
    { label: 'thead', value: 'thead', description: 'テーブルのヘッダー' },
    { label: 'tbody', value: 'tbody', description: 'テーブルのボディ' },
    { label: 'tfoot', value: 'tfoot', description: 'テーブルのフッター' },
    { label: 'tr', value: 'tr', description: 'テーブルの行' },
    { label: 'th', value: 'th', description: 'テーブルのヘッダーセル' },
    { label: 'td', value: 'td', description: 'テーブルのデータセル' },
    { label: 'col', value: 'col', description: '列の定義' },
    { label: 'colgroup', value: 'colgroup', description: '列のグループ' },
    { label: 'details', value: 'details', description: '詳細情報' },
    { label: 'summary', value: 'summary', description: '詳細の概要' },
    { label: 'dialog', value: 'dialog', description: '対話ボックス' },
    { label: 'template', value: 'template', description: 'テンプレート' },
    { label: 'slot', value: 'slot', description: 'スロット' },
];